### PR TITLE
Add SOCKS proxy support

### PR DESCRIPTION
**Pull request by dbevacqua**
Although this "works for me", it's still work in progress and needs at least some more tests in `test_http_session.py` to cover cases where `URLLib3Session` is configured with SOCKS proxies. Before going any further I wanted to verify the general approach.

One particular question is how to avoid warnings from importing `urlib3.contrib.socks` when `socks` (an optional dependency) is not available.

### CODE REVIEW

**Comment by hnousiainen** [comment]
I have a need to access AWS endpoints over SOCKS5 proxy and I've tested this modification successfully in that environment. Are you still working on this PR, and is there anything I could help with?

**Comment by zhan9san** [comment]
@dbevacqua 

Are you still working on this feature? Would you mind if I pick it up?

**Comment by dbevacqua** [comment]
@zhan9san please be my guest

**Comment by tim-finnigan** [comment]
Thank you for creating this PR. After bringing this up for discussion with the team we decided to continue tracking this request in https://github.com/boto/botocore/pull/2541 going forward, with the latest update here: https://github.com/boto/botocore/pull/2541#issuecomment-1666001438

**Pull request closed without merging**
