### PR TITLE
Iam string to dict

### PR DESCRIPTION
**Pull request by stealthycoin**
https://github.com/boto/boto3/issues/978

We decode the string for the AssumeRolePolicyDocument field in the response from get_role in iam.
https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L428-L456

The documentation currently cites its type as a string

cc @dstufft @kyleknap @jamesls @JordonPhillips 

### Changes to example:
screen shot 2017-02-15 at 5 37 06 pm

### Changes to parameter docs:
screen shot 2017-02-15 at 5 29 32 pm

### CODE REVIEW

**Comment by JordonPhillips** [comment]
It looks like this is a problem with all the returned iam policy docs, so it would be better to apply that to all return structures with `policyDocumentType`.

For reference, [here](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L428) is where we decode it.

**Comment by wchresta** [comment]
We ran into this documentation issue today. What is needed to get this merged? How can I help?

**Comment by chrispblink** [comment]
I think it's worth adding that this breaks [boto3-stubs[iam]](https://pypi.org/project/mypy-boto3-iam/) as they are automatically generated from boto docs.

**Comment by tim-finnigan** [comment]
After bringing this up for discussion the consensus was that [this comment](https://github.com/boto/botocore/pull/1154#issuecomment-282800323) from earlier still applies:

>It looks like this is a problem with all the returned iam policy docs ([another example](http://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.get_user_policy)), so it would be better to apply that to all return structures with `policyDocumentType`.

**Pull request closed without merging**
