### PR TITLE
Added EFS to AWS Config

### PR DESCRIPTION
**Pull request by mikegrima**
- Adds support for AWS::EFS::FileSystem
- Adds support for AWS::EFS::AccessPoint
- Features added to AWS Config as documented here: https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html

### CODE REVIEW

**Comment by nateprewitt** [comment]
Thanks for the PR, @mikegrima! Unfortunately, these files are maintained in a separate system owned by the service. We'll pass this request along to them to get things fixed in a future release.

**Comment by kdaily** [comment]
I opened this to track: https://github.com/aws/aws-sdk/issues/104

**Comment by kdaily** [comment]
FYI @mikegrima - https://github.com/aws/aws-sdk/issues/104#issuecomment-894477336

**Comment by kdaily** [comment]
FYI @mikegrima https://github.com/aws/aws-sdk/issues/104#issuecomment-900539950

**Pull request closed without merging**
