### PR TITLE
Allow botocore loading from zip

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/boto/boto3/issues/1770

### CODE REVIEW

**Comment by gliptak** [comment]
@stealthycoin @joguSD please review

**Comment by andrewdunai** [comment]
Why was this closed? Is there a different ticket where support for loading `boto3` from `.pyz` is implemented?

**Comment by gliptak** [comment]
@andrewdunai I closed my PR as committers didn't show interest

**Comment by andrewdunai** [comment]
It's a shame this is not getting enough attention. This functionality basically renders `boto3` useless for testing AWS lambda functions locally since `boto3` cannot be imported when running lambda ZIP as `python3 lambda.zip`.

**Comment by nikushi** [comment]
I've got the same problem that causes errors on AWS lambda when botocore is packaged within a zip file. I hope this issue could be improved.

**Comment by kojiromike** [comment]
@gliptak AWS can take a tremendously long time to follow up on pull requests. If you don't want to keep your attention on a months-or-years long open pull request, I'd be happy to take it over for you. Unless it's left open, I'm sure AWS will ignore it forever.

**Comment by gliptak** [comment]
@kojiromike yes I do close my PRs not receiving attention after about a month. Feel free to resubmit. You might have better success

**Comment by and3rson** [comment]
Wow, it's been more than a year.

**Pull request closed without merging**
