### PR TITLE
Botocore imagebuilder paginators

### PR DESCRIPTION
**Pull request by crashdummymch**
tested and verified paginators work with this fix.

### CODE REVIEW

**Comment by crashdummymch** [comment]
Not sure why this is failing the ci/cd tests need help triaging this.

**Comment by crashdummymch** [comment]
This is resolves botocore issue #2017

**Comment by swetashre** [comment]
@crashdummymch - Thank you for the PR. Have you had any chance to look at the failing tests ? For the ```ListComponents``` api the result_key is incorrect. Can you please correct it ? Please run the tests first locally to make sure its passing all the tests. You can see which file is failing for this code in the travis logs.

**Comment by crashdummymch** [comment]
I had not as I needed a little help trying to decifer the logs to determine
what the issue was. I will look to see if I can get this to pass with the
help you provided thanks

**Pull request closed without merging**
