### PR TITLE
Support client params from a single positional arg

### PR DESCRIPTION
**Pull request by jamesls**
This is an alternative to those that don't prefer to use
**kwargs for client calls.

I'd like to get some feedback on this before merging.  We've had some concern about using ``**kwargs``.   We'd also heard that using the `CamelCasing` in our ``**kwargs`` annoys tools such as pylint.  This adds an option to make calls via:

```
client = session.create_client('dynamodb')
client.describe_table({"TableName": "foo"})
```

thoughts?  cc @kyleknap @mtdowling @rayluo

### CODE REVIEW

**Comment by kyleknap** [comment]
Looks good. One thing that would be nice to check is that boto3, still works as expected. Maybe run the tests to make sure nothing is unexpectedly broken with the the resource interface. :ship:

**Comment by jamesls** [comment]
Ran boto3 tests against this change, they passed.

**Comment by kyleknap** [comment]
Cool. Good with me to merge then.

**Comment by rayluo** [comment]
Nice! Ship it! :shipit:

**Comment by wt** [comment]
FWIW, the following should already work without this change:

    client = session.create_client('dynamodb')
    client.describe_table(**{"TableName": "foo"})

Why not just rely on that?

**Comment by wt** [comment]
There seems to be an agreement with the original author of this PR (@jamesis) that it should not be merged (see #230). Perhaps this PR should be closed?

**Comment by jamesls** [comment]
Yeah, I think fi we don't get feedback additional feedback by tomorrow, we can go ahead and pass on this pull request for the time being.

**Comment by jamesls** [comment]
Closing due to lack of interest (https://github.com/boto/boto3/issues/230).  We can look at this again in the future if there's any future interest.

**Pull request closed without merging**
