### PR TITLE
Add shared example for sqs

### PR DESCRIPTION
**Pull request by kyleknap**
Also updated the formatting for a missing newline. Here is what it looks like:
screen shot 2015-12-15 at 10 23 44 am

cc @jamesls @mtdowling @rayluo @JordonPhillips

### CODE REVIEW

**Comment by JordonPhillips** [comment]
:boat:

**Comment by mtdowling** [comment]
Looks good... We should update the example source to remove the empty attribute hash though.

**Comment by kyleknap** [comment]
@mtdowling I got the example fixed.

**Comment by rayluo** [comment]
:ship:

**Comment by jamesls** [comment]
:shipit:

**Pull request merged**
