### PR TITLE
Add paginators for CloudWatch Logs

### PR DESCRIPTION
**Pull request by mjschultz**
This adds some paginators requested in https://github.com/boto/botocore/issues/613. I've verified them to the best of my ability with the services we use, but we don't have any subscription filters.

GetLogEvents is also strange because, it seems, that on the "last" page the `nextForwardToken` is intentially a self reference which causes botocore to raise `botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: [u'f/...']` exception.

Let me know what you think!

### CODE REVIEW

**Comment by mjschultz** [comment]
I elected to remove the `GetLogEvents` paginator for now since it's behavior is strange compared to most other APIs.

**Comment by jamesls** [comment]
Thanks.  Do you know if FilterLogEvents has the same issue as GetLogEvents?

**Comment by mjschultz** [comment]
It does not appear to have the same issue. The [AWS docs](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html) don't mention two tokens or have a `startFromHead` parameter.

**Comment by eldondevcg** [comment]
:+1: I have not tested this change myself, but it looks good. I didn't see verbose information about the string pattern in FilterLogEvents. Is it an exact string match? Does a 0-length pattern match all log lines?

**Comment by mjschultz** [comment]
@eldondevcg It looks like the `filterPattern` parameter takes inputs as documented in the [Filter and Pattern Syntax](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html) document.

Not providing the parameter or having it `filterPattern=''` both return the same number of results (for me).

I'm using this for VPC Flow Logs so if I provide a `filterPattern` like `'[version, account, eni, source, destination, srcip, destip, protocol="6", packets, bytes, windowstart, windowend, action="ACCEPT", flowlogstatus]'` it returns only the results where the protocol (8th space delimited field) is 6 and the action (13th field) is ACCEPT.

**Comment by jamesls** [comment]
Thanks!

**Comment by jstewmon** [comment]
I am getting `PaginationError` `Error during pagination: The same next token was received twice: ` with a `filter_log_events` paginator using boto3==1.2.3 and botocore==1.3.18, so it looks like the previously dismissed concern is actually a problem.

**Pull request merged**
