### PR TITLE
Handle the case where we receive a generic html error response

### PR DESCRIPTION
**Pull request by jamesls**
Fixes boto/boto3#339.

cc @kyleknap @JordonPhillips

### CODE REVIEW

**Comment by JordonPhillips** [comment]
What do you think about populating those values with the HTTP error codes? Otherwise CLI users are not going to have any idea what just happened.

**Comment by jamesls** [comment]
@JordonPhillips feedback incorporated.

**Comment by JordonPhillips** [comment]
:boat:

**Comment by kyleknap** [comment]
Looks good. :ship: Do you think that this fix also partially resolves this issue: https://github.com/aws/aws-cli/issues/1679 for when the proxy returns straight html?

**Comment by jamesls** [comment]
@kyleknap It should.  Looking at their output it looks like this should fix that case because we're getting an HTML error page back from the proxy.  Excellent.

**Pull request merged**
