### PR TITLE
Switch to codecov for coverage reports

### PR DESCRIPTION
**Pull request by jamesls**
Switch to codecov for coverage reports.

cc @kyleknap @JordonPhillips

### CODE REVIEW

**Comment by jamesls** [comment]
Sample coverage report: https://github.com/jmespath/jmespath.py/pull/106#issuecomment-199362262

The coverage diff has been really helpful.

**Comment by jamesls** [comment]
The low coverage number is because coverage.py isn't reading our top level .coveragerc file because we run our tests from the `tests/` directory.  We'll either need to copy the coveragerc file over to tests/ or possbily move the .coverage file to the top level directory.

**Comment by kyleknap** [comment]
:ship:

**Comment by JordonPhillips** [comment]
⛵

**Comment by jamesls** [comment]
success! Properly ignoring vendored/ files.

I'm going to go ahead and rebase and merge.

**Pull request merged**
