### PR TITLE
AWSHTTPSConnection: invoke the correct constructor

### LINKED ISSUE #1258: 'AWSHTTPSConnection' object has no attribute 'ssl_context'
Hi,

I'm getting the above error when trying to use Route53 service. I have investigated and concluded that the fault is [the copying of functions from AWSHTTPConnection to AWSHTTPSConnection](https://github.com/boto/botocore/blob/37bbdc3ffc40e43500d8e044b418947dce4f7482/botocore/awsrequest.py#L256-L261):

```python
# Now we need to set the methods we overrode from AWSHTTPConnection
# onto AWSHTTPSConnection.  This is just a shortcut to avoid
# copy/pasting the same code into AWSHTTPSConnection.
for name, function in AWSHTTPConnection.__dict__.items():
    if inspect.isfunction(function):
        setattr(AWSHTTPSConnection, name, function)
```

The problem is that this ends up overriding the `__init__` function too, so the `VerifiedHTTPSConnection` constructor is never invoked. I don't know why this worked in the past, or why it has become a problem recently. I have locally patched that file to add `and function.__name__ != '__init__'` to the `if` above, and copied manually the constructor to `AWSHTTPSConnection` (to invoke `VerifiedHTTPSConnection` constructor). Things seem to work fine now.

### PR DESCRIPTION
**Pull request by fsateler**
Fixes #1258

### CODE REVIEW

**Comment by fsateler** [comment]
Hi,

Is there anything I can do to help getting this patch merged?

**Comment by fsateler** [comment]
Friendly ping. Is there anything I can do to help getting this patch merged?

**Comment by Hernrup** [comment]
We were just about to provide the very same PR. Please merge or tell us if we can do anything to help. 

Please note that this patch seems to allow for replacing the bundled urllib with a newer version and fixing a multitude of bugs without dealing with the hassle of unbundling requests.

**Comment by tim-finnigan** [comment]
Thank you for creating this PR. However it is now outdated as Python 2.6 is no longer supported and for the reasons [mentioned here](https://github.com/boto/botocore/issues/1258#issuecomment-415928768) in the corresponding issue that is now closed. Please consider creating a new issue for anything related to this going forward.

**Pull request closed without merging**
