### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by caioagiani**
* `.changes/1.4.14.json` recieve → **receive**
* `CHANGELOG.rst` recieve → **receive**
* `botocore/data/resourcegroupstaggingapi/2017-01-26/service-2.json` recieve → **receive**
* `botocore/data/sagemaker/2017-07-24/service-2.json` recieve → **receive**
* `tests/unit/test_utils.py` test_does_not_redirect_unless_permanentredirect_recieved → **test_does_not_redirect_unless_permanentredirect_received**

### CODE REVIEW

**Review by nateprewitt — CHANGES_REQUESTED** [review]
Hi @caioagiani, lets leave the `.changes` and `botocore/data` directories alone. Those files are sourced externally and may be overwritten in a future update. Otherwise, we're happy to accept the remaining changes.

**Comment by caioagiani** [comment]
Hi @nateprewitt, if you think it's ok to keep errors de digitacao in the repository, ok!

**Comment by kdaily** [comment]
Hi @caioagiani,

The files in the `botocore/data` directory come from AWS service teams. Any changes made here would just get overwritten the next time the service makes an update to their API. I will be happy to let the SageMaker and Resources tagging teams know about these typographical errors!

The `.changes` as well is autogenerated; while having correct spelling in the past would be great, we won't make any changes there. However, we're exploring preventing these kinds of errors from happening in the first place. In `s3transfer` we've enabled spellcheck through `codespell`, which we could use to check the changelog entries before they're committed.

https://github.com/boto/s3transfer/blob/c5307a76c45f42f8d0688298f8c1ddb3a8c0fbce/.pre-commit-config.yaml#L27

If you can cherry pick the change to the test function name, we can move forward with merging this! Let me know if you need any assistance.

**Comment by nateprewitt** [comment]
We're going to close this as it hasn't seen changes in a few months. If anyone would like to open a PR containing only the utils change, we'll happily accept that. Thanks!

**Pull request closed without merging**
