### PR TITLE
set charset parameter to utf-8 for simpledb queries

### PR DESCRIPTION
**Pull request by memory**
Addresses https://github.com/boto/boto3/issues/354

This is my first time mucking about in models.py so feedback is definitely appreciated.

### CODE REVIEW

**Comment by memory** [comment]
Note that the failure in `tests.functional.test_endpoints.test_service_name_matches_endpoint_prefix` appears to also be present in develop/HEAD and is not AFAICT related to this PR.

**Comment by memory** [comment]
Ugh, okay.  Any suggestions on where might be a reasonable place to shim this in?

**Comment by memory** [comment]
okay, doing this the sleazy way: special-casing SDB inside endpoint.py.

**Comment by memory** [comment]
(I'm on vacation this week; please don't close this just yet -- will deal with the coverage issues when I get back.)

**Comment by memory** [comment]
@JordonPhillips I believe this is ready for review now.

**Comment by memory** [comment]
Poke? :)

**Comment by jamesls** [comment]
Assigning to @stealthycoin.  This might be an issue with our query serializers.

**Comment by memory** [comment]
PR https://github.com/boto/botocore/pull/1285 addresses this in a more systematic fashion; closing this as there is not ever going to be a reason to merge it.  Thanks @stealthycoin!

**Comment by woodrow** [comment]
@memory can you help me understand how to reproduce this error? I am wondering if #1285 is not the right fix (I don't know that the header needs to be signed) but I want to do more research before proposing a fix.

**Comment by memory** [comment]
@woodrow see the commentary at boto/boto3#354 -- updating a simpledb item attribute with any xml-valid utf-8 character should produce the behavior with a pre-#1285 boto3, e.g.:

```
sdb.put_attributes(DomainName = 'foo',
                   ItemName = 'foo',
                   Attributes = [{'Name': 'foo', 'Value': 'bär', 'Replace': True}])
```

**Pull request closed without merging**
