### PR TITLE
introduce PFS

### PR DESCRIPTION
**Pull request by chrisdlangton**
discussion https://github.com/boto/botocore/issues/1822

### CODE REVIEW

**Comment by chrisdlangton** [comment]
I've checked each file this PR touches in the codecov reports and all the LOC codecov says are not covered are not any LOC this PR changed...

**Comment by chrisdlangton** [comment]
code review?
@jamesls 
@JordonPhillips 
@awstools 
@kyleknap

**Comment by joguSD** [comment]
@chrisdlangton I think at this point trying to offer configuration for every knob in the SSLContext is too much and it's probably a better approach to just allow a custom SSLContext to be passed as a client configuration.

**Comment by chrisdlangton** [comment]
@joguSD thank you for commenting.

Basically a custom SSLContext was impossible, i'll evaluate the new botocore state once the PR that removes the vendored `requests` is merged

**Comment by chrisdlangton** [comment]
@joguSD it is curious you mention this, should I also refactor out the `use_ssl` and expect an end-user to know how to construct the primitives themselves?
no...
that is crazy fora framework/library.. it's nonsensical to suggest frameworks/libraries should not introduce a _feature flag_.

THis PR is introducing a _feature flag_ so an end-user can simply chose to _enforce_ the feature called _pfs_ (Perfect Forward Secrecy as it is known) which is actually just a select ciphersuite that (few) people actually know the correct options to use to do this (probably why not many people are doing this today, it's damn hard)

So i fundamentally disagree, we _should_ definitely be abstracticting away these extremely complex features behind a feature flag, botocore does this is almost every line of code.. the most analogous feature flag is the `use_ssl` flag...

**Comment by chrisdlangton** [comment]
@joguSD it is curious you mention this, should I also refactor out the use_ssl and expect an end-user to know how to construct the primitives themselves?

no...

that is crazy..

For a framework/library, it is nonsensical to suggest frameworks/libraries should not introduce a feature flag.

This PR is introducing a _feature flag_ so an end-user can simply chose to enforce the feature called pfs (Perfect Forward Secrecy as it is known) which is actually just a select ciphersuite that (few) people actually know the correct options to use to do this (probably why not many people are doing this today, it's damn hard)

So i fundamentally disagree, we should definitely be abstracticting away these extremely complex features behind a feature flag, botocore does this is almost every line of code.. the most analogous feature flag is the use_ssl flag...

**Pull request closed without merging**
