### PR TITLE
Add client-method-called event to botocore

### PR DESCRIPTION
**Pull request by kyleknap**
This event will help with the issue with the boto3 dynamodb customizations where if a dictionary gets passed to botocore, it gets modified.

cc @jamesls

### CODE REVIEW

**Comment by jamesls** [comment]
:shipit:  My only feedback is that I'd prefer to call this event name something else.  Ideally this event name communicates the fact that this is the place to construct the api params that will be used for serialization.  Something like, `want-api-params`, `client-params-wanted`, etc.

**Comment by kyleknap** [comment]
How about ``provide-client-params`` or ``client-params-provided``? I think for consistency the later is better based on verb tense

**Comment by jamesls** [comment]
My vote would be the first choice.  I see the providing of the client params as something the event is asking the handlers to do, so the past tense doesn't make sense yet since the handlers haven't yet provided the client params.

**Comment by kyleknap** [comment]
Sounds good. I will make the change.

**Comment by jamesls** [comment]
:shipit:

**Pull request merged**
