### PR TITLE
SSM waiter for command to complete

### PR DESCRIPTION
**Pull request by dimzak**
Waits for an ssm command invocation to complete.

Closes https://github.com/boto/botocore/issues/1744

### CODE REVIEW

**Comment by TheSkorm** [comment]
Can this get a look over botocore team? Other PRs that just add waiter config have merged before without added integration tests. I just wrote pretty much the same waiter and found this while preparing my own PR.

**Comment by myniva** [comment]
I've tested this waiter in one of my projects and it seems to work as expected.

**Comment by siolta** [comment]
Can we get this merged ?  Would like to start using it without having to copy it into my own custom waiter.

**Comment by xeroxnir** [comment]
Is this feature ready to be merged?

**Comment by stobrien89** [comment]
Hi all,

Thanks again for the request. We are now submitting requests for paginators and waiters upstream so that all AWS SDKs benefit from a consistent implementation. I will pass on the request for these waiters to the service team. We will also update the guidance in the contributing guide to better reflect this policy. I've added an issue to track this here:

aws/aws-sdk#90

Thanks again for bringing this to our attention!

**Comment by TheSkorm** [comment]
@stobrien89 I'm a little bit confused as to how this is meant to work. This is an open PR with working code that solves the problem that many many teams have, and could be merged right now into botocore. 

aws-sdk project on the otherhand seems to be an abstract issue tracker - that I assume would generate tickets/issues for some to implement these exact changes in every sdk project.

Is the intent that we wait another 3 years before this issue is looked at in aws-sdk project, before someone the creates a PR in this repo again, and waits another 3 years for it to accepted? 

The aws-sdk seems like a good idea to gain consistency between SDKs but I have to ask, is that important? because this appears to make getting changes to botocore even more difficult than it was before.

I just want to build cool shit.

**Comment by stobrien89** [comment]
Hi All,

Just wanted to touch base— I haven't heard anything from the SSM team on this just yet, but I bumped our internal ticket on this in hopes of expediting a response.  Any updates are sent to me by email, so I'll let you know as soon as I hear anything!

**Comment by TheSkorm** [comment]
Thanks @stobrien89, I appreciate it

**Comment by kiararip91** [comment]
hi @stobrien89 is there any update on this? I am also face the same issue and an improvement for this would be really helpful

**Comment by stobrien89** [comment]
Hi @kiararip91,

I haven't received a response from the team yet after bumping the ticket.  I'm working on finding a point of contact for ssm feature requests so I can hopefully provide a meaningful update.  I'll let everyone know as soon as I hear anything!

**Comment by kiararip91** [comment]
thanks @stobrien89

**Comment by stobrien89** [comment]
Hi all,

Just received an update from the SSM team today— They've added this request to their backlog, which is a good sign, but I there is not an estimated date for completion as of right now.  I'll provide any additional updates I receive from them!

**Comment by NK74** [comment]
Opened, Tested and Fixed in 2019
2020 ... 2021 ... 2022 ??

Nothing happened, please help @stobrien89  @aBurmeseDev @mattsb42-aws

**Pull request closed without merging**
