### PR TITLE
check for empty strings for Region (and others) and provide sensible fall-back

### LINKED ISSUE #1627: 'region' value never checked for empty string, nor any sane default applied
The api makes various calls to resolve service endpoints but at no stage does it actually check for empty strings nor does it provide the sensible default which per AWS docs is supposed to be 'us-east-1'. As a result of never checking for inputs programs throw ValueError on malformed endpoints like 'https://s3..amazonaws.com' - notice the double dot.

### PR DESCRIPTION
**Pull request by tb3088**
fixes #1627

### CODE REVIEW

**Comment by tb3088** [comment]
addresses #1460 to some extent. The codebase relies extensively on testing for just None which is sloppy.

**Comment by JordonPhillips** [comment]
Validating an empty region would be a breaking change in the case where you provide an endpoint url or where you are making unsigned requests with a service where region does not impact the url. We explicitly don't want a default region - it is not safe to assume where somebody should run a bit of code.

**Comment by tb3088** [comment]
> it is not safe to assume where somebody should run a bit of code.

ok, I'll stipulate to that. However the rest of the diffs are valid since now the Boto API intercepts and treats as errors values that are empty string whereas previously it just blithely continued even though that value was clearly wrong.

**Comment by tb3088** [comment]
What's with the rampant failure to check for 'empty' objects? There must be a zillion IF statements that should only proceed if the objects has a value that is non-empty. 'is [not] None' is an insufficient test.

**Comment by JordonPhillips** [comment]
It's generally better to be explicit, unless you have a reason not to. When `None` is the default value we check for that explicitly,  because otherwise you start implicitly supporting any falsey values.

**Comment by swetashre** [comment]
> Validating an empty region would be a breaking change in the case where you provide an endpoint url or where you are making unsigned requests with a service where region does not impact the url. We explicitly don't want a default region - it is not safe to assume where somebody should run a bit of code.

I am closing this PR based upon this comment.

**Pull request closed without merging**
