### PR TITLE
Fix typo: DEFAUT -> DEFAULT

### PR DESCRIPTION
**Pull request by tipabu**

### CODE REVIEW

**Comment by swetashre** [comment]
@tipabu - Thank you for the PR. The change looks good. Can you resolve the conflict so that we can merge the PR ?

**Comment by tipabu** [comment]
> Can you resolve the conflict so that we can merge the PR ?

Thanks for letting me know about the conflict; done.

**Comment by joguSD** [comment]
I think we're a little gun shy on making typo fixes like this in variable names. I know in the past it's caused issues for some people despite these variables not being public interfaces really. At the very least to feel comfortable with this change we would need an alias for the old spelling.

**Comment by nateprewitt** [comment]
Going to resolve this as we haven't seen changes in the last several months and it no longer runs against CI. Please feel free to reopen if there are more changes to review. Thanks!

**Pull request closed without merging**
