### PR TITLE
Add possibility of modifying retry_config

### PR DESCRIPTION
**Pull request by taraslayshchuk**
Hi, according to issue #882 with num_retries there is some improvements to change retry_config over Api which include: max_attempts, delay.base, delay.growth_factor.

Usage example:

``` python
retry_config = {
    "max_attempts": 10,
    "base": 15,
    "growth_factor": 60
}
boto3_config = botocore.client.Config(retry_config=retry_config)
```

What do you think about it?

### CODE REVIEW

**Comment by jamesls** [comment]
Not opposed to the feature in general.

I wonder how much of the retry logic we should expose though.  Once it's exposed we can't change/remove it.  I'm slightly concerned that base/growth_factor are too low level, and might make it hard to support other types of backoff calculations in the future besides exponential backoff.

What do others think?

**Comment by taraslayshchuk** [comment]
In general if we made some changes in `~/.aws/models/_retry.json` it will cause changes in all scripts, which used on same PC with same user. So if you want made some changes for one script and did not want make for another you have to write some wrapper which will put this json-file before script run and delete it after run (and add some logic to delete json-file if script fails). It is not simple solution and anyway we need have some possibility to make changes in retry logic from code and use it per script.

**Comment by copumpkin** [comment]
I'd love this, since I've had some cases where the default number of retries wasn't enough.

**Comment by rafaelcaricio** [comment]
Please just expose the `max_attempts` to make this feature move on.

**Comment by lapointexavier** [comment]
@rafaelcaricio @taraslayshchuk I was wondering, is this still relevant? I was looking for a solution to this and came across this PR

**Comment by rafaelcaricio** [comment]
@lapointexavier  Yes, would be nice to have this options available.

**Comment by lapointexavier** [comment]
@rafaelcaricio What's missing to get this merged, better patch coverage?

**Comment by thenoid** [comment]
Can we get this merged please?

**Comment by spstarr** [comment]
Would like this merged also:

Merely just trying to use a filter will trigger API limits when I have way too many volumes, snapshots etc:

` sched_volumes = list(ec2.volumes.filter(Filters=vol_filter))`
...
botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeVolumes operation (reached max retries: 4): Request limit exceeded.

Anything that can help me override this retry limit would help vs me having to use python @retry decorator fun.

**Comment by thehesiod** [comment]
time to get this or something related to this puppy landed

**Comment by kyleknap** [comment]
@taraslayshchuk We recently merged a PR: https://github.com/boto/botocore/pull/1260 that allows you to set the maximum retry attempts. It provides a similar functionality to yours except it does not expose the base or growth factor. We were not quite comfortable exposing those two parameters quite yet and wanted to start small with just maximum retry attempts before including some of the more granular/implementation related configurations. For this reason, I am closing out this PR, but thanks again for the contribution!

**Pull request closed without merging**
