### PR TITLE
Revert SQS protocol changes

### PR DESCRIPTION
**Pull request by nateprewitt**
Roll back recent SQS changes.

### CODE REVIEW

**Review by kyleknap — APPROVED** [review]
:ship:

**Comment by bblommers** [comment]
Hi @nateprewitt, I was just looking into fixing this for `Moto`.
Will the JSON format be reintroduced at some point in the future, or is the SQS-service going to stick with XML for now?

**Comment by bblommers** [comment]
Appreciate the info @nateprewitt - having a timeline/estimate would be very useful.

Do you know if other XML-based services, like EC2 or S3, will get the same treatment?

**Comment by bblommers** [comment]
Awesome, thanks @nateprewitt!

**Pull request merged**
