### PR TITLE
Properly handle boolean query string arguments

### PR DESCRIPTION
**Pull request by srri**
Fixes https://github.com/aws/aws-cli/issues/2030
Read there for background. Also let me know if you think we need a test for this
cc: @JordonPhillips

### CODE REVIEW

**Comment by JordonPhillips** [comment]
Always need new tests to prevent regressions

**Comment by srri** [comment]
Working on one, thanks

**Comment by srri** [comment]
Added a couple tests also fixed a test that was being executed but not checked. Can we re-run codecov?

**Comment by srri** [comment]
Tests added, good to go

**Comment by jamesls** [comment]
I think these would make the most sense as shared protocol tests (https://github.com/boto/botocore/blob/develop/tests/unit/protocols/input/rest-xml.json) so other SDKs can pick them up.

**Comment by srri** [comment]
Updated test to live in `procotols/input/rest-xml.json`

**Comment by jamesls** [comment]
:shipit:  Looks good to me.

**Comment by JordonPhillips** [comment]
⛵

**Pull request merged**
