### PR TITLE
Eliminate __file__ for importlib.resources

### PR DESCRIPTION
**Pull request by philipkimmey**
# Background
We have an internal tool that we distribute to all developers and we're looking to improve how we distribute that package.

Everything works fine with a `.pex`-style approach, but eliminating the `__file__`-oriented assumptions would allow us to use [PyOxidizer](https://pyoxidizer.readthedocs.io/en/stable/) which we hope will reduce the extra ~400ms of overhead that the pex-based approach introduces. (400ms isn't the end of the world but isn't ideal for a CLI tool our team is using all day.)

Here's a somewhat random grab bag of relevant links:

- https://github.com/boto/boto3/issues/1770
- https://github.com/boto/botocore/pull/1969
- https://github.com/certifi/python-certifi/pull/116
- https://pyoxidizer.readthedocs.io/en/latest/oxidized_importer_behavior_and_compliance.html#no-file

# Code

This currently this just contains failing tests that demonstrate the issue. I recognize the test code is pretty rough but couldn't come up with a more clever way to demonstrate the issue (since `botocore` will usually already be imported in the Python interpreter when this test is run.). (It's possible that the proposed [Subinterpreter](https://www.python.org/dev/peps/pep-0554/) stuff would make that possible but that's theoretical and I'm not familiar enough to know if it would actually even help.)

### CODE REVIEW

**Comment by mattsb42-aws** [comment]
Some historical conversation on this if it helps: https://github.com/boto/botocore/issues/1950

**Comment by mattsb42-aws** [comment]
It is still an issue: https://github.com/boto/botocore/search?q=__file__

**Comment by tcyrus** [comment]
I'm not sure if that search is the best example, as the only code that should cause issues with bundling is the code in the `botocore` directory. That being said, [it's still an issue](https://github.com/boto/botocore/search?q=__file__+path%3Abotocore).

**Comment by aBurmeseDev** [comment]
Thank you all for chiming in. This was brought up to discuss with the team recently and per team discussion, eliminating _file_ at the base level module might be a breaking change and would have to find a better approach to accomplish it. Closing for now.

**Pull request closed without merging**
