### PR TITLE
Assume role to acquire credentials

### PR DESCRIPTION
**Pull request by dump247**
Adds configuration options to a profile that supports assuming a role to acquire AWS credentials. This uses the same options as the AWS CLI currently supports, with a couple of differences:

1. The cli does caching of the role credentials, but that doesn't seem appropriate for botocore. I don't know the appropriate way to expose that functionality.
2. No support for `mfa_serial` option. This would require some mechanism to prompt for the MFA token.
3. The CLI requires the `source_profile` option, but this PR makes that optional. If not provided, access/secret key are taken from the current profile.

Addresses https://github.com/boto/boto3/issues/263

### CODE REVIEW

**Comment by DanyC97** [comment]
+1

funny i banged my head against the wall to understand if is boto3 or botocore which doesn't support role_arn

**Comment by pdecat** [comment]
Works perfectly for me, thanks!

**Comment by tianx2** [comment]
:+1: this would close https://github.com/boto/boto3/issues/263

**Comment by dump247** [comment]
Any update on this? It would really make our lives easier since we are moving to a multi-account setup accessed via roles.

**Comment by jamesls** [comment]
Taking a look at this.  One of things I think we may want to do is have the assume role provide be a separate class like it is in the CLI.  This would make it easier for customers to remove this provider or adjust its priority if they wanted.  It would also help as a base class if AssumeRoleWithSAML is ever added.

**Comment by dump247** [comment]
@jamesls Seems like a good idea, but wouldn't that mean parsing the credentials file twice or is that not a concern? Is there any canonical way to share that information between the providers?

**Comment by dump247** [comment]
One potential issue with making this a separate provider, outside of parsing the credentials file twice, would be that the new provider would have to be a higher priority than the existing shared credentials provider. This would impact the CLI since it inserts its provider before the shared credentials provider. The CLI would need to be updated. With the current implementation, the CLI should continue to work as it currently does.

**Comment by jamesls** [comment]
Essentially I'm proposing just moving the assume role provider from the CLI into botocore with the appropriate changes (removing hard coded file cache etc).  Once botocore has this functionality, there's really no benefit in also having it in the CLI.  So the CLI would no longer have the assume role credential provider.

Given the CLI locks to a specific version of botocore, this should be an ok change to make provided we coordinate the corresponding changes to the CLI.

**Comment by jamesls** [comment]
I should mention I don't mind taking a crack at this to see how feasible this is.

**Pull request closed without merging**
