### PR TITLE
Make Session.create_client() thread safe

### LINKED ISSUE #577: ValueError: Unknown component: endpoint_resolver
I'm seeing a very sporadic error which I'm hoping someone here can explain.  See stack trace below.  This is happening less than 5 times a day on a site that's getting maybe a million requests a day, so it's pretty rare, but I'd like to understand what's going on and see if there's a way to fix it.  I should also mention that the EC2 instance this code runs on has an IAM role associated with it, and gets its creds automatically through that mechanism.

Any idea what might be going wrong here?  Thanks.

$ pip freeze | grep boto
boto3==0.0.19
botocore==1.0.0b1

  File "/home/ubuntu/nasuni/nasuni/utils/aws/s3.py", line 82, in list_bucket_contents
    bucket = boto3.resource('s3', region_name=settings.AWS_REGION).Bucket(bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 87, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 270, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 192, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 833, in create_client
    endpoint_resolver = self.get_component('endpoint_resolver')
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 741, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 857, in get_component
    raise ValueError("Unknown component: %s" % name)
ValueError: Unknown component: endpoint_resolver

### PR DESCRIPTION
**Pull request by jdufresne**
Fixes #577
Fixes boto/boto3#801

### CODE REVIEW

**Comment by jamesls** [comment]
Thanks for the pull request.  Is the rest of the `create_client` call thread safe?  I would have expected race conditions in `create_client` given there's still shared state.

Is there any downsides to just locking the entire `create_client` method?

**Comment by jdufresne** [comment]
The change was sufficient for my application to stop failing with "ValueError: Unknown component: endpoint_resolver" when using the boto3 storage engine of [django-storages](https://github.com/jschneier/django-storages). I tried to avoid excessive or overeager locking. However, you'll know better than me. If you think locking the entire `create_client()`, I'll make the necessary changes.

**Comment by jdufresne** [comment]
Updated PR to now lock then entire `Session.create_client()` method. Thanks.

**Comment by leonsmith** [comment]
Is there anything I can assist with in getting this merged?

In the process of testing the above PR to confirm this resolves the issue, but my thread/locking knowledge is limited.

**Comment by jdufresne** [comment]
Yeah, I figured if there was an elegant solution upstream, it would make sense to push efforts there. Although, since the original discussion, not movement has occurred. So I don't know at this point. Take the approach you see as best.

**Pull request closed without merging**
