### PR TITLE
Update service-2.json to be clearer about nextToken element

### PR DESCRIPTION
**Pull request by jonathanwcrane**
Update more visible part of documentation to make it clearer (and less likely to miss this tidbit).

### CODE REVIEW

**Comment by rayluo** [comment]
A side note. This PR is the effort from @jonathanwcrane to address the issue boto/boto3#281

We will figure out how to incorporate this request.

**Comment by jonathanwcrane** [comment]
Thanks, @rayluo

**Comment by jamesls** [comment]
Sorry about the confusion.  As per our [contributing guidelines](https://github.com/boto/botocore/blob/develop/CONTRIBUTING.rst) we aren't able to accept pull requests to these JSON files as they are auto generated from an upstream source.  There would get lost the next time we sync with that source.  I will follow up with the doc team to the source updated (http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html#CWL-FilterLogEvents-request-NextToken).

**Comment by jonathanwcrane** [comment]
Interesting.  So there's an upstream from the upstream (this is upstream from boto3), but that upstream is not open source?

**Comment by jamesls** [comment]
There is an upstream source that the SDKs pull from where this change will need to be made.  I've followed up with the necessary team to get this documentation updated.  I'll update this once we pull the new JSON model.

**Comment by jonathanwcrane** [comment]
Thanks @jamesls

**Pull request closed without merging**
