### PR TITLE
Simplify CI config

### PR DESCRIPTION
**Pull request by hugovk**
* ~Test Python 3.8 beta, before it's October release~

* `sudo:` is no longer needed on Travis CI: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

* Default to Trusty, explicitly use Xenial where needed

### CODE REVIEW

**Comment by asherf** [comment]
@hugovk python 3.8 was release... you can probably update the PR to use the GA version.

**Comment by hugovk** [comment]
Thanks, updated!

**Comment by hugovk** [comment]
Python 3.8 was added in https://github.com/boto/botocore/pull/1922, so this PR now simply simplifies the CI config.

**Comment by hugovk** [comment]
Merge conflict resolved.

**Pull request closed without merging**
