### PR TITLE
Document streaming payload inputs

### PR DESCRIPTION
**Pull request by kyleknap**
Fixes https://github.com/boto/boto3/issues/477

Here are samples of how it looks:
screen shot 2016-03-04 at 1 45 42 pm

cc @jamesls @JordonPhillips

### CODE REVIEW

**Comment by jamesls** [comment]
Do we define SeekableStream anywhere?

Is it worth just saying it's a `file` type?

**Comment by kyleknap** [comment]
I just made up a class name. We can call it ``file`` if we want. I just want to make the point that we accept file like objects that must be seekable. Thoughts?

**Comment by JordonPhillips** [comment]
It's unfortunate that there's no IO base class that is defined by seek support. Maybe call it `file` and inject something in the doc string about it requiring seek?

**Comment by jamesls** [comment]
Yeah something like that would work.  My main concern is that someone sees `SeekableStream`, thinks that's some base class/interface they need to implement, and can't find any information about that.

**Comment by kyleknap** [comment]
Alright how about this one?

**Comment by jamesls** [comment]
:shipit:  Looks good.

**Pull request merged**
