### PR TITLE
Include Content-MD5 header when body is empty

### PR DESCRIPTION
**Pull request by wimglenn**
Closes https://github.com/boto/botocore/issues/1979

### CODE REVIEW

**Comment by swetashre** [comment]
@wimglenn - Can you write a test case to make sure the header is present ?

**Comment by wimglenn** [comment]
@swetashre  Please check the CI failure.  It does not look related to my change at all.

**Comment by wimglenn** [comment]
@swetashre  Is there anything more I can do to help get this bug fixed?

**Comment by wimglenn** [comment]
@swetashre  Is it possible to get a review or get this patch merged? What's the hold-up?

**Comment by joguSD** [comment]
@wimglenn Conceptually, these changes sound alright to me. We need to do some confirmation on our side around all the exact expectations around the content-md5 of empty bodies. We also have some changes in the works around this code path that will end up conflicting and might end up fixing this issue anyways. We'll follow up on this after those changes go out.

**Comment by nateprewitt** [comment]
Hi @wimglenn, just wanted to follow up from our last comment. The changes referenced are now in place. Please feel free to rebase this on top of the master branch and we can take another look. Thanks!

**Comment by jangrewe** [comment]
@nateprewitt Maybe you can have a look at https://github.com/boto/botocore/pull/2181 - this fix works fine for our issue.

**Comment by wimglenn** [comment]
@nateprewitt  @joguSD  @swetashre  Rebased on develop, and updated after the refactor. I hope this doesn't languish again.

**Comment by nateprewitt** [comment]
Thanks again for this PR, @wimglenn! I'm merging this into a feature branch for a couple more tweaks and we're going to try to get this merged into live asap.

**Comment by radekwlsk** [comment]
@wimglenn @nateprewitt FYI: In Django (and especially `django-storages` with `boto3`) when using `ContentFile("")` as empty file stub to create S3 object, i.e. for presigned URL upload, this change makes it fail on save to S3.

```
TypeError: Unicode-objects must be encoded before hashing
  ...
  File "django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "storages/backends/s3boto3.py", line 451, in _save
    obj.upload_fileobj(content, ExtraArgs=params)
  File "boto3/s3/inject.py", line 619, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "s3transfer/futures.py", line 265, in result
    raise self._exception
  File "s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "botocore/client.py", line 652, in _make_api_call
    handler, event_response = self.meta.events.emit_until_response(
  File "botocore/hooks.py", line 360, in emit_until_response
    return self._emitter.emit_until_response(aliased_event_name, **kwargs)
  File "botocore/hooks.py", line 243, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "botocore/utils.py", line 2219, in conditionally_calculate_md5
    md5_digest = calculate_md5(body, **kwargs)
  File "botocore/utils.py", line 2196, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
  File "botocore/utils.py", line 2209, in _calculate_md5_from_file
    md5.update(chunk)
```

I suppose making it `ContentFile(b"")` will resolve that issue, as with string it uses `StringIO` instead of `BytesIO` buffer. But maybe text content could be handled here? To encode it first, before calculating md5.

**Comment by wimglenn** [comment]
@radekwlsk  Yes I would think that's a bug in `django-storages`, that code should use BytesIO in the first place. Better to make sure you're sending bytes and not text, it's outside of the responsibility for botocore to guess any encoding to use.

**Comment by nateprewitt** [comment]
Hi @radekwlsk, thanks for bringing this to our attention! It looks like `django-storages` has been violating the API constraint but happened to be getting away with it only for empty files. The [boto3 interface](https://github.com/boto/boto3/blob/develop/boto3/s3/inject.py#L588) they're using states that the fileobj supplied but be in binary mode to work correctly.

@wimglenn is correct that this will likely need to be fixed in that project since guessing around file encodings leads to a lot of unexpected failures.

**Comment by radekwlsk** [comment]
> Hi @radekwlsk, thanks for bringing this to our attention! It looks like `django-storages` has been violating the API constraint but happened to be getting away with it only for "falsey" files. The [boto3 interface](https://github.com/boto/boto3/blob/develop/boto3/s3/inject.py#L588) they're using states that the fileobj supplied must be in binary mode to work correctly.

Thanks for quick response! I've already reported that isssue in `django-storages`. If there is no response I may create a PR myself then.

**Pull request merged**
